on: 
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"  # <--- espace ajouté ici

  pull_request:
    branches:
      - main
      - "release/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      
      - name: Run Tests
        run: npm test
